### ISSUE TITLE
Fix typo in `title` variable

### ISSUE THREAD

**Issue by icaoberg** [icaoberg/cs-scholars2024-fair#27]
https://github.com/icaoberg/cs-scholars2024-fair/blob/2c6b5d1621728c8832b6454ccca9da6ce82e1ea4/streamlit_app.py#L11

Change line 

```
title = 'FAIR Assessment of HuBMAP Data'
st.write(title)
```

to 

```
title = '# Self-assessment of HuBMAP published resources'
st.write(title)
```

**Comment by icaoberg** [comment]
@Xinlin3 any updates on this task?

**Comment by josiah-edm** [comment]
Fixed the misspelling in the title.
